name: Deploy to Firebase Hosting on PR

on:
  pull_request:

permissions:
  contents: read          # allows reading repo contents
  pull-requests: write    # allows posting PR comments and deployment links
  id-token: write         # required for Firebase authentication (OIDC)
  deployments: write      # needed to create preview deployments
  actions: read           # safe default for reading GitHub Actions metadata

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache node_modules for faster builds
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests using Vitest
      - name: Run tests
        run: npm run test

      # Build the project using Vite
      - name: Build project
        run: npm run build

      # Deploy to Firebase Hosting (Preview Channel for PR)
      - name: Deploy to Firebase Hosting (Preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIGNESHCOINHOSTING }}
          projectId: vigneshcoinhosting
