name: Deploy to Firebase Hosting on PR

on:
  pull_request:

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache node_modules for faster CI
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # Install dependencies
      - run: npm ci

      # Run tests using Vitest
      - run: npm run test

      # Build project using Vite
      - run: npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIGNESHCOINHOSTING }}
          projectId: vigneshcoinhosting
